grase_radmin_homepage:
    #path:     /hello/{name}
    path:     /
    defaults: { _controller: GraseRadminBundle:Default:index }

grase_security:
    resource: "@GraseRadminBundle/Controller/SecurityController.php"
    type:     annotation

avanzu_admin_logout:
      path: /logout

avanzu_admin_profile:
    path: /profile/
    defaults: {}

