clone:
  tags: true
build:
  image: 'grasewwwbuild'
  commands:
    - dch -b -v $(git describe |tr '-' '.') "Nightly"
    - git commit -a -m "Nightly Build Commit"
    - git-buildpackage -us -uc

publish:
  sftp:
    host: localhost
    username: artifacts
    password: $$SFTP_PASSWORD
    files:
      - *.deb
      - *.build
      - *.changes
      - *.dsc
      - *.tar.xz
    destination_path: /home/artifacts/grase-www-portal/
