clone:
  tags: true
build:
  image: 'grasewwwbuild'
  commands:
    - mkdir /root/.cache
    - cp -a /drone/bower /root/.cache/ || true
    - rm -rf /drone/bower
    - dch -b -v $(git describe |tr '-' '.') "Nightly"
    - git commit -a -m "Nightly Build Commit"
    - git-buildpackage -us -uc --git-export-dir=./build-area
    - cp -a /root/.cache/bower /drone/

cache:
  mount:
    - /drone/bower

publish:
  sftp:
    host: $$SFTP_HOST
    username: artifacts
    password: $$SFTP_PASSWORD
    files:
      - './build-area/*.deb'
      - './build-area/*.build'
      - './build-area/*.changes'
      - './build-area/*.dsc'
      - './build-area/*.tar.xz'
    destination_path: /home/artifacts/grase-www-portal/
